[tool.poetry]
name = "wisest"
version = "0.8.0"
description = ""
authors = ["narumi <toucans-cutouts0f@icloud.com>"]
packages = [{ include = "wise" }]

[tool.poetry.dependencies]
python = "^3.10"
httpx = "^0.27.0"
pydantic = "^2.4.2"
loguru = "^0.7.0"
click = "^8.1.3"
tqdm = "^4.66.1"

[tool.poetry.group.dev.dependencies]
mypy = "^1.8.0"
pytest = "^7.2.0"
pytest-cov = "^4.1.0"
ruff = "^0.1.8"
toml = "^0.10.2"
types-tqdm = "^4.66.0.20240417"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
wise = "wise.cli:cli"

[tool.ruff]
exclude = ["build"]
line-length = 120
target-version = "py39"

[tool.ruff.lint]
select = [
    "B", # flake8-bugbear
    "C", # flake8-comprehensions
    "E", # pycodestyle Error
    "EM", # flake8-errmsg
    "F", # Pyflakes
    "FA", # flake8-future-annotations
    "I", # isort
    "N", # pep8-naming
    "NPY", # NumPy-specific rules
    "PTH", # flake8-use-pathlib
    "S", # flake8-bandit
    "TRY", # raise-vanilla-args
    "UP", # pyupgrade
    "W", # pycodestyle Warning

]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401", "F403"]
"test_*.py" = ["S101"]

[tool.ruff.lint.isort]
force-single-line = true

[tool.pytest.ini_options]
filterwarnings = ["ignore::DeprecationWarning"]
