[tool.poetry]
name = "wise"
version = "0.5.1"
description = ""
authors = ["narumi <toucans-cutouts0f@icloud.com>"]

[tool.poetry.dependencies]
python = "^3.9"
pydantic = "^2.4.2"
loguru = "^0.7.0"
click = "^8.1.3"
python-dotenv = "^1.0.0"
slack-sdk = "^3.21.3"
python-telegram-bot = "^20.3"
telegraph = "^2.2.0"
markdown = "^3.4.3"
yfinance = "^0.2.22"
retry = "^0.9.2"
tqdm = "^4.66.1"

[tool.poetry.group.dev.dependencies]
black = "^23.9.1"
flake8 = "^5.0.4"
isort = "^5.12.0"
pytest = "^7.2.0"
toml = "^0.10.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
wise = "wise.cli:cli"
