[tool.poetry]
name = "wise"
version = "0.6.0"
description = ""
authors = ["narumi <toucans-cutouts0f@icloud.com>"]

[tool.poetry.dependencies]
python = "^3.9"
pydantic = "^2.4.2"
loguru = "^0.7.0"
click = "^8.1.3"
tqdm = "^4.66.1"
requests = "^2.31.0"

[tool.poetry.group.dev.dependencies]
black = "^23.9.1"
flake8 = "^5.0.4"
isort = "^5.12.0"
pytest = "^7.2.0"
pytest-cov = "^4.1.0"
toml = "^0.10.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
wise = "wise.cli:cli"
