[tool.poetry]
name = "wise"
version = "0.2.1"
description = ""
authors = ["なるみ <toucans-cutouts0f@icloud.com>"]

[tool.poetry.dependencies]
python = "^3.9"
pydantic = "^1.10.7"
loguru = "^0.7.0"
click = "^8.1.3"
influxdb-client = "^1.36.1"
python-dotenv = "^1.0.0"
slack-sdk = "^3.21.3"
visafx = "^0.1.1"
python-telegram-bot = "^20.3"

[tool.poetry.group.dev.dependencies]
flake8 = "^5.0.4"
isort = "^5.12.0"
pytest = "^7.2.0"
toml = "^0.10.2"
yapf = "^0.32.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
