name: Cron

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *"

jobs:
  cron:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run
        run: |
          pip install .
          python scripts/add_usd.py >> target_usd.txt
          python scripts/same_currency.py >> same_currency.txt
      - uses: danielmcconville/gist-sync-file-action@v2.0.0
        with:
          gistPat: ${{ secrets.GIST_TOKEN }}
          action: update
          filename: target_usd.txt
          gistId: ${{ vars.GIST_ID }}
          createIfNotExists: true
      - uses: danielmcconville/gist-sync-file-action@v2.0.0
        with:
          gistPat: ${{ secrets.GIST_TOKEN }}
          action: update
          filename: same_currency.txt
          gistId: ${{ vars.GIST_ID }}
          createIfNotExists: true
