name: Cron

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *"

jobs:
  cron:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        python-version: ["3.9"]
        poetry-version: ["1.7.1"]
    steps:
      - uses: actions/checkout@v4
      - uses: abatilo/actions-poetry@v2
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: poetry
      - name: Run
        run: |
          poetry install
          poetry run python scripts/add_usd.py >> output.txt
          poetry run python scripts/same_currency.py >> same_currency.txt
      - uses: danielmcconville/gist-sync-file-action@v1.0.0
        with:
          gistPat: ${{ secrets.GIST_TOKEN }}
          action: update
          filename: output.txt
          gistId: ${{ vars.GIST_ID }}
          createIfNotExists: true
      - uses: danielmcconville/gist-sync-file-action@v1.0.0
        with:
          gistPat: ${{ secrets.GIST_TOKEN }}
          action: update
          filename: same_currency.txt
          gistId: ${{ vars.GIST_ID }}
          createIfNotExists: true
