name: Tag

on:
  push:
    branches: ["main"]

jobs:
  tag:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: narumiruna/auto-tag-version@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-repository: ${{ github.repository }}
